apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: foobar-api-tcp
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`foobar.local`)
      services:
        - name: foobar-api
          port: 80
  tls:
    passthrough: true
